[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.95

[font]
normal = { family = "BigBlueTermPlus Nerd Font", style = "Regular" }
size = 12

[general]
import = [
  "~/.config/alacritty/themes/gotham.toml"
]
