[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 1

[font]
# normal = { family = "BigBlueTermPlus Nerd Font", style = "Regular" }
 normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
size = 14

[general]
import = [
  #"~/.config/alacritty/themes/nord.toml"
   "~/.config/alacritty/themes/gotham.toml"
  # "~/.config/alacritty/themes/vscode.toml"
]
