#!/bin/bash

ta() {
  tmux attach -t $1
}

tc() {
  tmux new -s $1
}

tk() {
  tmux kill-session -t $1
}

trc() {
  tk $1
  tc $1
}

colours() {
  for i in {0..255}; do
    printf "\x1b[38;5;${i}mcolour${i}\x1b[0m\n"
  done
}

ghub() {
  git config user.name "yrachid"
  git config user.email "anuar.yasser@gmail.com"
}

gpg_reset() {
  gpgconf --kill gpg-agent
}

weather() {
  curl wttr.in/${1:-"POA"}
}

cpf() {
  $(which python || which python3) -c "
from random import randrange

def calculate_digit(numbers):
  numbers_length = len(numbers) + 1
  partial_result = sum([(numbers_length - idx) * x for idx, x in enumerate(numbers)]) % 11
  return 11 - partial_result if partial_result > 2 else 0

def generate_cpf():
  numbers = [randrange(10) for _ in range(0, 9)]
  first_digit = calculate_digit(numbers)
  second_digit = calculate_digit(numbers + [first_digit])
  return map(str, numbers + [first_digit] + [second_digit])

print(''.join(generate_cpf()), end='')
"
}
