#!/bin/bash

ta() {
  tmux attach -t $1
}

tc() {
  tmux new -s $1
}

tk() {
  tmux kill-session -t $1
}

trc() {
  tk $1
  tc $1
}

colours() {
  for i in {0..255}; do
    printf "\x1b[38;5;${i}mcolour${i}\x1b[0m\n"
  done
}

ghub() {
  git config user.name "yrachid"
  git config user.email "anuar.yasser@gmail.com"
}

gpg_reset() {
  gpgconf --kill gpg-agent
}

weather() {
  curl wttr.in/${1:-"POA"}
}
