call plug#begin()

  Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
  Plug 'ctrlpvim/ctrlp.vim'
  Plug 'neoclide/coc.nvim', { 'branch': 'release' }
  Plug 'fcpg/vim-farout'
  Plug 'vim-airline/vim-airline'
  Plug 'vim-airline/vim-airline-themes'
  Plug 'Yggdroot/indentLine'
  Plug 'navarasu/onedark.nvim'
  Plug 'airblade/vim-gitgutter'
  Plug 'wincent/terminus'
  Plug 'dcampos/nvim-snippy'

call plug#end()

" Sets a color scheme that does not burn the eyes so much.
syntax enable
colorscheme farout

runtime vimrc.d/ale.vim
runtime vimrc.d/coc.vim
runtime vimrc.d/ctrlp.vim
runtime vimrc.d/editor.vim
runtime vimrc.d/emmet.vim
runtime vimrc.d/nerdtree.vim
runtime vimrc.d/rainbow.vim
runtime vimrc.d/vim-test.vim
runtime vimrc.d/keymap.vim
