#!/bin/bash

BUNDLE_PATH=$HOME/.othman853/.vim/bundle

function content_after_last_slash() {
  URL=$1
  echo ${URL##*/}
}

if [ ! -z "$1"  ]; then

  cd $BUNDLE_PATH

  PLUGIN_REPO=$1
  PLUGIN_NAME=$(content_after_last_slash $PLUGIN_REPO | sed 's/\.git//')

  git submodule add -f $PLUGIN_REPO $BUNDLE_PATH/$PLUGIN_NAME

  read -p "Commit new plugin? (y/n)" -n 1 -r
  echo ""

  if [[ $REPLY =~ ^[Yy]$ ]]; then
    git add .
    git commit -m "Adding $PLUGIN_NAME plugin to vim"
    git push origin master
  fi

else
  echo "You forgot the plugin url."
fi

